version: "3"

services:
  daf:
    image: uport/daf:latest
    ports:
      - 8080:8080/tcp
    environment:
      - DAF_CONFIG=/config/config.js
      - DAF_DATA_STORE=/config/database.sqlite
      - DAF_GRAPHQL_API_KEY=
      - DAF_INFURA_ID=5ffc47f65c4042ce847ef66a3fa70d4c
      - DAF_SECRET_KEY=d72629cfd01e8e64762808a37e29d63103ef5cb7e92888afb9d4c0a6426c933e
    command:
      [
        "graphql",
        "--port=8080"
      ]
    volumes:
      - .:/config
