packages:
  - packages/*

ignoredBuiltDependencies:
  - bufferutil
  - core-js
  - core-js-pure
  - nx
  - protobufjs
  - secp256k1
  - utf-8-validate

onlyBuiltDependencies:
  - puppeteer
  - sqlite3

prefer-workspace-packages: true
